#!/bin/bash
# global functions used in every sripts
# edit wit ftp-remote-edit Atom

source /opt/busy4me/busy-config # busy variables from there

if [[ $SCRIPT == "" ]]; then
	SCRIPT="busy-functions"
fi
#echo "SCRIPT=$SCRIPT"

if [[ $JOB == "" ]]; then
	JOB="----"
fi
#echo "JOB=$JOB"

busy4me_log () {
if ! [ -f /var/log/busy4me.log ];then
	touch /var/log/busy4me.log
	chmod 777 /var/log/busy4me.log
fi
}

# set echo types
echotest() {
    	echo "test"
}

echoerror() {
    printf "${lred}[ ERROR ]${lred} %s${nocolor}\\n" "$@" 1>&2;
}

echowarning() {
    printf "${lyel}[ WARNING ] %s ${nocolor}\\n" "$@" 1>&2;
}

echoinfo() {
    printf "${lblu}[ INFO ]${lcya} %s ${nocolor}\\n" "$@" 1>&2;
}

echoconfirm() {
    printf "${mag}[ CONFIRMATION ]${lmag} %s ${nocolor}\\n" "$@" 1>&2;
}

echosuccess() {
    printf "${mag}[ SUCCESS ]${lmag} %s ${nocolor}\\n" "$@" 1>&2;
}

echofunc() {
    printf "${lwhi}${lbckbla}[ FUNCTION ]${nocolor}${lwhi} %s${nocolor}\\n" "$@" 1>&2;
}

echook() {
    printf "${lgre}[ OK ]${gre} %s${nocolor}\\n" "$@" 1>&2;
}

# screenshot to local catalog
scrot_local () {
code="-"$1
mkdir /opt/busy/scrot/$SCRIPT 2>/dev/null
scrot1="/opt/busy/scrot/$SCRIPT/$(date +%Y%m%d-%H%M%S)-$JOB-scrot$DISPLAY$code.jpg"
scrot -q 50 $scrot1
echo -e "\e[33m code: \e[35m" $1 "\e[33m scrot file: \e[35m" $scrot1 "\e[0m" | logline
}

move_mouse () {
  # mouse walking around... with visual efect from A to B
  A_x=167
  A_y=193
  xdotool mousemove --sync --clearmodifiers $A_x $A_y
  sleep 0.3
  B_x=573
  B_y=157
  xdotool mousemove --sync --clearmodifiers $B_x $B_y
  sleep 0.3
  xdotool mousemove --sync --clearmodifiers 754 22
  sleep 0.3
  xdotool mousemove --sync --clearmodifiers 759 27
  sleep 0.3
  xdotool mousemove --sync --clearmodifiers 764 32
  sleep 0.3
}

# mark machine for root to reboot in next cronjob
# see root's crontab
mark_for_reboot () {
	echo -e "\e[101m mark it for root to reboot ...\e[0m" | logline
	echo "1" > /tmp/busy4me-reboot
}

cron-enable () {
echo ""
}

start () {
	screen -ls
	_TASK=$1
	if [ -z "$_TASK" ]; then
		screen -dmS frame00$DISPLAY '/opt/busy4me/frame00' # default task to run: frame00
		sleep 2
		screen -ls
		return
  fi
#	screen -dmS $_TASK$DISPLAY '/opt/busy4me/fb/$_TASK'
	screen_start=$(screen -dmS $_TASK$DISPLAY '/opt/busy4me/fb/fb-walking-around')
#	echo $screen_start
	screen -ls
}

stop () {
	screen -ls
	_TASK=$1
	if [ -z "$_TASK" ]; then
		for scr in $(screen -ls | awk '{print $1}'); do screen -S $scr -X kill; done
		screen -wipe
#		screen -S frame00$DISPLAY -X kill # kill frame00
#		screen -ls
		return
	fi
	echo -e "\e[95m stop $_TASK in screen $DISPLAY...\e[0m"
	screen_stop=$(screen -S $_TASK$DISPLAY -X kill)
	if [[ $screen_stop == *"There are several suitable screens"* ]]; then
		echo -e "\e[41m Error... There are several suitable screens... kill them... \e[0m"
		pkill screen
	fi
	screen -ls
}

start-walking () {
	echo -e "\e[32m start fb-walking-around in screen $DISPLAY...\e[0m"
	screen_start=$(screen -dmS fb-walking-around$DISPLAY '/opt/busy4me/fb/fb-walking-around')
	echo $screen_start
}

stop-walking () {
	screen -ls
	echo -e "\e[95m stop fb-walking-around in screen $DISPLAY...\e[0m"
	screen_stop=$(screen -S fb-walking-around$DISPLAY -X kill)
	if [[ $screen_stop == *"There are several suitable screens"* ]]; then
		echo -e "\e[41m Error... There are several suitable screens... kill them... \e[0m"
		pkill screen
	fi
	screen -ls
}

stop-mouse-move-around () {
echo -e "\e[95m stop stop-mouse-move-around in screen $DISPLAY...\e[0m"
screen -S mouse-move-around$DISPLAY -X kill
}

stop-fb-save-my-groups () {
	screen_stop=$(screen -S fb-save-my-groups$DISPLAY -X kill)
	if [[ $screen_stop == *"There are several suitable screens"* ]]; then
		echo -e "\e[41m Error... There are several suitable screens... kill them... \e[0m"
		pkill screen
	fi
}

start-fb-save-my-groups () {
	screen_start=$(screen -dmS fb-save-my-groups$DISPLAY '/opt/busy4me/fb/fb-save-my-groups')
	echo $screen_start
}

function status () {
_TASK=$1
screen -ls
_TASK_VAR=$(echo "$_TASK" | tr '-' '_' | tr ':' '_')
if ! screen -list | grep -q "$_TASK"; then
		_VAL="false"
		IFS= read -r "$_TASK_VAR" <<<"false"
	else
		_VAL="true"
		IFS= read -r "$_TASK_VAR" <<<"true"
fi
#echo $_TASK_VAR
#export "$_TASK_VAR=$_VAL"
#ptintf -v $_TASK_VAR %s "$_VAL"# create variable named $_TASK_VAR with value $_VAL
#echo $_TASK_VAR
#echo -e "\e[33m$_TASK_VAR=$_VAL\e[0m"
#if ! screen -list | grep -q "fb-walking-around$DISPLAY"; then
#		echo -e "\e[33m ... screen fb-walking-around$DISPLAY not exists! \e[0m"
		#screen -S ScreenName -X quit
#	else
#
#		echo -e "\e[33m ... screen fb-walking-around$DISPLAY exists \e[0m"
#fi

}

function COMMENT () {
echo -e "\e[44m SCRIPT=$SCRIPT Func: COMMENT \e[0m" | logline
case $1 in
	all|--all|-a)
		CRON disable
		stop-mouse-move-around
		stop-walking
		screen_task="/opt/busy4me/fb/fb-post COMMENT "$1
		screen_name="busy"$DISPLAY
		echo -e "\e[43m\e[30m start screen session: \e[0m\e[95m screen -dmS $screen_name $screen_task \e[0m" | logline
		screen -S $screen_name -X kill # kill screen on this display
		screen -dmS $screen_name $screen_task
		CRON enable
	;;
	*fb*com*permalink*)
		CRON disable
		stop-mouse-move-around
		stop-walking
		screen_task="/opt/busy4me/fb/fb-post COMMENT "$1
		screen_name="busy"$DISPLAY
		echo -e "\e[43m\e[30m start screen session: \e[0m\e[95m screen -dmS $screen_name $screen_task \e[0m" | logline
		screen -S $screen_name -X kill # kill screen on this display
		screen -dmS $screen_name $screen_task
		CRON enable
	;;
	*)
		echo -e "... \e[33m" $1 "\e[31m ... wrong argument ...\e[0m" | logline
	;;
esac
}

# set crontab
set_crontab () {
task=$1
case $task in
	"all"|"fb-post -c all"|"fb-post")
		empty=""
		cron=$(crontab -l)
		case $cron in
			*$task*)
			echo -e "\e[32m crontab already has task: \e[33m $task ... \e[0m" | logline
			;;
			$empty)
			echo -e "\e[31m crontab is empty ... add task: \e[33m $task \e[0m" | logline
			crontab -l | echo "*/5 * * * * export DISPLAY=:0 && /opt/busy4me/fb/fb-post -c all" | crontab - | logline
			;;
			*)
			echo -e "\e[31m crontab is not contains \e[33m $task ... add task: $task \e[0m" | logline
			crontab -l | echo "*/5 * * * * export DISPLAY=:0 && /opt/busy4me/fb/fb-post -c all" | crontab - | logline
			;;
		esac
		echo -e "\e[32m crontab: \e[33m" | logline
		crontab -l | logline
		echo -e "\e[0m"
	;;
	*)
		echo -e "declare task ... \e[33m" $task "\e[31m ... wrong argument ...\e[0m" | logline
	;;
esac
}

function CRON () {
echo -e "\e[44m SCRIPT=$SCRIPT Func: CRON \e[0m" | logline
action=$1
job=$2
echo -e "action: " $action
echo -e "job: " $job

case $1 in
	disable|--disable)
		echo -e "\e[91m # disable \e[95m crontab job ... $job\e[90m"
		crontab -l | sed "/^[^#].*export DISPLAY=$DISPLAY && \/opt\/busy4me\/fb\/$job/s/^/#/" | crontab -
		crontab -l | sed "/^[^#].*export DISPLAY=$DISPLAY && \/opt\/busy4me\/busy/s/^/#/" | crontab -
		crontab -l
	;;
	enable|--enable)
		echo -e "\e[32m # enable \e[95m crontab job ... $job \e[90m"
		echo -e "\e[32m # enable \e[95m crontab job ... $job \e[90m"
		crontab -l | sed "/^#.*export DISPLAY=$DISPLAY && \/opt\/busy4me\/fb\/$job/s/^#//" | crontab -
		crontab -l | sed "/^#.*export DISPLAY=$DISPLAY && \/opt\/busy4me\/busy/s/^#//" | crontab -
		crontab -l
	;;
	status|--status)
		crontab -l
	;;
	setup|--setup)
		echo -e "setup job: \e[33m $job \e[0m"
		set_crontab $job
	;;
	*)
 		echo -e "\e[41m # bad argument \e[95m $1 \e[33m"
	;;
esac
}

# disable crontab job
disable-crontab-job () {
echo ""
}

# enable crontab job
enable-crontab-job () {
echo "enable-crontab-job empty"
}

function FIND () {
echo -e "\e[44m SCRIPT=$SCRIPT Func: FIND \e[0m" | logline
echo -e "action: "$action "job: "$job
}


function DB () {
# syntax: busy DB SELECT * FROM table WHERE column=value
# eg. busy DB SELECT * FROM fb_groups WHERE admins=0
echo -e "\e[44m SCRIPT=$SCRIPT Func: DB \e[0m" | logline
action=$1 # SELECT
tab=$2; tab=$(echo $tab | sed 's/\\//')
data=$3

target=$2; target=$(echo $target | sed 's/\\//')
table=$4
clause=$5 # WHERE
condition=$6 # column=value

echo -e "action=$action tab=$tab target=$target table=$table clause=$clause condition=$condition"

case $1 in
	SELECT)
		sqlite3 -header -column $user_db "SELECT $target FROM $table $clause $condition;"
	;;
	--show|-s)
		echo -e "\e[91m arg: \e[95m $1 $2 \e[0m show tables: \e[35m"
		sqlite3 $user_db "SELECT name FROM sqlite_master WHERE type='table';"
		echo -e "\e[33mread table:\e[95m $tab\e[0m"
		sqlite3 -header -column $user_db "SELECT * from '$tab';"
	;;
	--drop-table|--drop)
		echo -e "\e[41m \e[0m\e[31m Warning! ... \e[33m drop table:\e[95m $tab\e[0m"
		sqlite3 $user_db "DROP TABLE '$tab';"
	;;
	--clear-data|--clear|--delete)
		echo -e "\e[41m \e[0m\e[31m Warning! ... \e[33m delete data from:\e[95m $tab\e[0m"
		sqlite3 $user_db "DELETE FROM '$tab';"
	;;
	--insert-test)
		echo -e "\e[43m \e[0m\e[33m Insert test data into table: \e[95m $tab\e[0m"
	sqlite3 $user_db "INSERT INTO '$tab' (name,first_name,middle_name,last_name,user_name,email,pass,fb_lang,post_lang)
	VALUES (
	'Firstname Lastname',
	'Firstname',
	'Middlename',
	'Lastname',
	'UserName',
	'username@emailprovider.com',
	'',
	'English',
	'German,English'
	);"
	sqlite3 $user_db "INSERT INTO 'fb_plan' (name) VALUES ('name of group');"
	;;
	--create-table|--create)
	sqlite3 $user_db "SELECT 1;"
	#create sqlite3 TABLE 'fb_user' in user database
	case $tab in
		socialmedia)
			sqlite3 $user_db "CREATE TABLE socialmedia (
			id INTEGER UNIQUE PRIMARY KEY,
			short TEXT,
			name TEXT,
			url TEXT,
			lang TEXT,
			label TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			;;
		fb_user)
			sqlite3 $user_db "CREATE TABLE fb_user (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			first_name TEXT,
			middle_name TEXT,
			last_name TEXT,
			user_name TEXT,
			email TEXT UNIQUE,
			pass TEXT,
			fb_lang TEXT,
			post_lang TEXT,
			label TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			;;
		fb_posts)
			sqlite3 $user_db "CREATE TABLE fb_posts (
			id INTEGER UNIQUE PRIMARY KEY,
			url TEXT UNIQUE,
			owner TEXT,
			PostDate DATE,
			CheckDate DATE,
			CheckCounter INTEGER,
			CommCounter INTEGER,
			lock INTEGER,
			label TEXT,
			LabelCounter INTEGER,
			who TEXT,
			comment TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# posts that created in the fb groups, posts collected from user Activity Log
			# url is usualy a permalink
		;;
		fb_groups)
			#create sqlite3 TABLE 'fb_groups' in user database
			sqlite3 $user_db "CREATE TABLE fb_groups (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			url TEXT UNIQUE,
			members INTEGER,
			admins INTEGER,
			lang TEXT,
			CatName TEXT,
			CatID TEXT,
			MyStatus TEXT,
			date DATE,
			DateId TEXT,
			label TEXT,
			privacy TEXT,
			history TEXT,
			description TEXT,
			KeyWord TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# MyStatus: joined, pending, ban, requested, admin, moderator
			# DateId: insert, check,
			# privacy: public, closed, secret
		;;
		fb_group__metadata)
			sqlite3 $user_db "CREATE TABLE fb_group__metadata (
			id INTEGER UNIQUE PRIMARY KEY,
			what TEXT,
			url TEXT,
			name TEXT,
			date DATE,
			status TEXT,
			confirm INTEGER,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# fb_group__metadata: part of url after '*.com/' eg. fb_group_AdChicago (from https://www.facebook.com/AdChicago)
			# what: like, admin, moderator, member, post, video, event, comment, review
			# name: can be part of user's (or page's) url eg. /JohnSmith234 (with slash) or real name eg. John Chris Smith
			# date: when added to the table
			# status: posted, deleted
			# confirm: 1,2...n how many times the status is confirmed
			# stat1: if 'what' is 'member' how many posts detected, if 'what' is 'event' how many 'display' detected
			# eg. table fb_group_AdChicago
			# id | what  | url                   | name                          | date       | status | confirm | stat1 | stat2 |
			# 1  | name  | /AdChicago            | Adevertisment in Chicago Il.  | 2019-05-10 | ok     | 2       | 1     | 1     |
			# 2  | post  | /permalink/1234509876 | /JohnSmith234                 | 2019-05-10 | del    | 5       | 0     | 1     |
			# 3  | admin | /StephenBusyman       | /StephenBusyman               | 2019-05-10 | ok     | 1       | 1     | 0     |
			# 4  | event | /events/0192837465    | /AgnesCaptain                 | 2019-05-10 | ban    | 4       | 267   | 2     |
			# 5  | member| /JoannaLikeME         | Joanna Bird                   | 2019-05-11 | active | 72      | 23    | 456   |
			# 6  | page  | /permalink/2938475601 | /JohnSmith234                 | 2019-05-11 |detected| 4       |
			# 7  | lang  | /permalink/1234509876 | german                        | 2019-05-01 |detected| 2       |
			sqlite3 $user_db "INSERT INTO fb_page__metadata (what,url,name,date,status,confirm,stat1,stat2)
			VALUES (
			'admin',
			'/StephenBusyman1',
			'Stephen Busyman',
			Date('now'),
			'ins',
			'1',
			'0',
			'0'
			);"
		;;
		fb_people)
			#create sqlite3 TABLE 'fb_friends' in user database
			sqlite3 $user_db "CREATE TABLE fb_people (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			url TEXT UNIQUE,
			lang TEXT,
			date DATE,
			DateId TEXT,
			label TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
		;;
		fb_friends)
			#create sqlite3 TABLE 'fb_friends' in user database
			sqlite3 $user_db "CREATE TABLE fb_friends (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			url TEXT UNIQUE,
			lang TEXT,
			date DATE,
			DateId TEXT,
			label TEXT,
			position INTEGER,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# fb_friends contains all friends collected from user's friends page (url: *.com/AgnesCaptain/friends)
		;;
		fb_user__UrlName)
			sqlite3 $user_db "CREATE TABLE fb_user__UrlName (
			id INTEGER UNIQUE PRIMARY KEY,
			what TEXT,
			url TEXT,
			name TEXT,
			date DATE,
			status TEXT,
			confirm INTEGER,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# fb_user_UrlName contains info from any user wall page eg. fb_user_JohnSmith234 (from url)
			#
			sqlite3 $user_db "INSERT INTO fb_user_UrlName (what,url,name,date,status,confirm,stat1,stat2)
			VALUES (
			'admin',
			'Stephen Busyman',
			Date('now'),
			'0',
			'0'
			);"
			# insert test table data
		;;
		fb_pages)
			#create sqlite3 TABLE 'fb_pages' in user database
			sqlite3 $user_db "CREATE TABLE fb_pages (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			url TEXT UNIQUE,
			lang TEXT,
			likes INTEGER,
			date DATE,
			DateId TEXT,
			label TEXT,
			created INTEGER,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# fb_pages contains all fanpages discovered or owned by the user
			# collected from user's pages (url: *.com/AgnesCaptain/pages)
		;;
		fb_page__metadata)
			sqlite3 $user_db "CREATE TABLE fb_page__metadata (
			id INTEGER UNIQUE PRIMARY KEY,
			what TEXT,
			url TEXT,
			name TEXT,
			date DATE,
			status TEXT,
			confirm INTEGER,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# examples:
			# fb_page__metadata: part of url after '*.com/' eg. fb_page_CarsAndDreams (from https://www.facebook.com/CarsAndDreams)
			# what: like, admin, post, video, event, comment, review
			# name: can be part of user's (or page's) url eg. /JohnSmith234 (with slash) or real name eg. 'John Chris Smith'
			# date: when added to the table
			# eg. table fb_page_CarsAndDreams
			# id | what  | url                | name            | date       | status | confirm | stat1 | stat2 |
			# 1  | post  | /posts/1234509876  | /JohnSmith234   | 2019-05-10 | top    | 2       | 1     | 1     |
			# 2  | admin | /StephenBusyman1   | Stephen Busyman | 2019-05-10 | active | 3       | 1     |
			# 3  | event | /events/0192837465 | /AgnesCaptain   | 2019-05-10 | del    | 3       | 1     |
			# 4  |analyst| /JoannaLikeME      | Joanna Bird     | 2019-05-10 | active | 1
			sqlite3 $user_db "INSERT INTO fb_page__metadata (what,url,name,date,status,confirm,stat1,stat2)
			VALUES (
			'admin',
			'JoannaLikeME',
			'Joanna Bird',
			Date('now'),
			'insert',
			'1',
			'0',
			'0'
			);"
			# insert test data
		;;
		fb_plan)
			#create sqlite3 TABLE 'fb_plan' in user database
			sqlite3 $user_db "CREATE TABLE fb_plan (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			url TEXT UNIQUE,
			date DATE,
			DateId TEXT,
			status TEXT,
			label TEXT,
			posted INTEGER,
			stat1 INTEGER,
			stat2 INTEGER
			);"
			# status: bump, posted, banned, deleted
		;;
		yo_user)
			#create sqlite3 TABLE 'yo_user' YouTube user
			sqlite3 $user_db "CREATE TABLE yo_user (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			first_name TEXT,
			middle_name TEXT,
			last_name TEXT,
			user_name TEXT,
			email TEXT UNIQUE,
			pass TEXT,
			lang TEXT,
			post_lang TEXT,
			label TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
		;;
		in_user)
			#create sqlite3 TABLE 'in_user' Instagram user
			sqlite3 $user_db "CREATE TABLE in_user (
			id INTEGER UNIQUE PRIMARY KEY,
			name TEXT,
			first_name TEXT,
			middle_name TEXT,
			last_name TEXT,
			user_name TEXT,
			email TEXT UNIQUE,
			pass TEXT,
			lang TEXT,
			post_lang TEXT,
			label TEXT,
			stat1 INTEGER,
			stat2 INTEGER
			);"
		;;
		all)
		DB --create-table socialmedia
		DB --create-table fb_user
		DB --create-table fb_posts
		DB --create-table fb_groups
		DB --create-table fb_group__metadata
		DB --create-table fb_people
		DB --create-table fb_friends
		DB --create-table fb_user__UrlName
		DB --create-table fb_pages
		DB --create-table fb_page__metadata
		DB --create-table fb_plan
		DB --create-table yo_user
		DB --create-table in_user
		;;
		*)
			echo -e "$1 ... \e[41m wrong table name: \e[0m\e[95m $2 \e[33m\e[0m"
		;;
	esac
	;;
	--update-data|--update|-ud)
		case $tab in
			groups|fb_groups)
				# update data from Facebook groups
				echo -e "\e[33m  ... CRON disable \e[0m"
				CRON disable
				stop-mouse-move-around
				echo -e "\e[33m  ... stop-walking \e[0m"
				stop-walking
				case $3 in
					category|--category|-cat|-c)
					# screen -dmS fb-groups-$3\:$4$DISPLAY '/opt/busy4me/fb/fb-groups $3 $4'
					/bin/bash /opt/busy4me/fb/fb-groups $3 $4
					;;
					--key|--key-random|--key-table)
					screen_task="/opt/busy4me/fb/fb-groups "$3" "$4
#					/bin/bash /opt/busy4me/fb/fb-groups $3 $4
					;;
					--collect-info)
					screen_task="/opt/busy4me/fb/fb-collect-info "$3" "$4
#					/bin/bash /opt/busy4me/fb/fb-collect-info $3 $4
					;;
					--save-my-groups)
					screen_task="/opt/busy4me/fb/fb-save-my-groups"
#					/bin/bash /opt/busy4me/fb/fb-save-my-groups
					;;
					'')
						echo -e "\e[41m bad argument ... \e[0m\e[95m $3 $4 \e[33m\e[0m"
					;;
					*)
						echo -e "\e[41m # wrong --method argument ... \e[0m\e[95m $3 $4 \e[33m\e[0m"
					;;
				esac
				screen_name="busy"$DISPLAY
				echo -e "\e[43m\e[30m start screen session: \e[0m\e[95m screen -dmS $screen_name $screen_task \e[0m" | logline
				screen -S $screen_name -X kill # kill screen on this display
				screen -dmS $screen_name $screen_task
				CRON enable
			;;
			fb_pages)
				CRON disable
				stop-mouse-move-around
				stop-walking
				case $3 in
					--save-my-pages)
						/bin/bash /opt/busy4me/fb/fb-save-my-pages
					;;
					*)
						echo -e "\e[41m wrong --method argument ... \e[0m\e[95m $3 $4 \e[33m\e[0m"
					;;

				esac
				CRON enable
			;;
			fb_friends)
				CRON disable
				stop-mouse-move-around
				stop-walking
				case $3 in
					--save-my-friends)
						/bin/bash /opt/busy4me/fb/fb-save-my-friends
					;;
					*)
						echo -e "\e[41m wrong --method argument ... \e[0m\e[95m $3 $4 \e[33m\e[0m"
					;;

				esac
				CRON enable
			;;
			*)
			echo -e "$1 ... \e[41m wrong table name: \e[0m\e[95m $2 \e[33m\e[0m"
			;;
		esac
	;;
	*)
	echo -e "\e[41m # ... ... ... ... bad argument ... \e[0m\e[95m $1 \e[33m\e[0m"
	;;
esac
}

function SYSTEM () {
case $1 in
	--clip-clear|-cc)
	xclip -selection clipboard /opt/busy/files/blank
	[[ $? -eq 0 ]] && echoconfirm "xclip cleared..."
	;;
	*)
		echo -e "\e[41m # bad argument \e[95m $1 \e[33m"
	;;
esac
}

function _extip () {
  # what is my external IP
  # ip
_EXTIP=$(curl -s "http://whatismyip.akamai.com/")
echo $_EXTIP
}
