#!/bin/sh
# config file

PROJECT="busy4me"
BR01="google-chrome" # Browser 01
PROC01="chrome" # process 01
SPOT01="facebook" # spot 01
SPOT01url="http://facebook.com" # url 01
SPOT02url="http://localhost"
SPOT03="terminal"
# BR01x=825 #BROWSER_01 size x
# BR01y=682 #BROWSER_01 size y
BR01x=1160 #BROWSER_01 size x, changed for 1280x768
BR01y=852 #BROWSER_01 size y,  changed for 1280x768
POSITION_x="137" # position x
POSITION_y="-81" # position y
BUSYUSER="busyman"
