#!/bin/sh
# Autoupdate if changed...
# Upgrade if needed...
# curl -s -v -X HEAD http://busy4.me/opt/busy4me/windows-init 2>&1 | grep '^< Last-Modified:'
SCRIPT=fb-init
LOGFILE=/var/log/busy4me.log
SAVE_DIR=/opt/busy/fb # with user permision 777
PROJECT_DIR=/opt/busy4me/fb # with root permision 755, read only for users

mkdir -p $SAVE_DIR 2>/dev/null

logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $USER $SCRIPT - $line" | tee -a $LOGFILE
    done
}

shake() {
xdotool key --delay 200 Page_Down End Page_Up Home
}

echo "$(date +%F' '%T) $USER $SCRIPT start.............................................."
echo "start..." | logline

if [ $USER = "root" ]
	then
	echo "Do not run as root! exit..." | logline
	exit
fi

if [ -f /opt/busy4me/fb/fb-config ];then
    . /opt/busy4me/fb/fb-config
	else
	echo "There is no fb_config file!... stop." | logline
	exit 1
fi

kd=600 # key delay [miliseconds]
to=2 # zenity messages time out [seconds]
BR01="google-chrome" # Browser 01
PROC01="chrome" # process 01
SPOT01="facebook" # spot 01
SPOT01url="http://facebook.com" # url 01
BR01x=825 #BROWSER_01 size x
BR01y=982 #BROWSER_01 size y

# Clean google-chrome busyman data... just in case...
echo "Clean google-chrome busyman data..." | logline
	rm -rf /home/$BUSYUSER/.config/google-chrome/Default
	rm -rf /home/$BUSYUSER/.cache/google-chrome
	rm -rf /home/$BUSYUSER/.config/google-chrome/Singleton*



# open transparent xtrminal
#echo "pkill xterm... cancelled temporary..." | logline
#xdotool search --onlyvisible --class xterm windowkill | logline
#echo "open transparent xterm...." | logline
#xterm -maximize & 2>/dev/null
#echo "wait for xterm and set window on top...." | logline
#xdotool search --sync --onlyvisible --class xterm windowactivate | logline
#echo "Always on top...." | logline
# xdotool key Alt_L+space l t
#wmctrl -i -r $(wmctrl -l | grep -i busyman@ | awk '{print $1}') -b add,above
#echo "set transparent xterm...." | logline
#transset -a 0 | logline

xdotool mousemove 800 600
echo "... * kill existing windows: BR01=$BR01 SPOT01=$SPOT01 PROC01=$PROC01..." | logline
xdotool search --onlyvisible --class "$BR01" windowkill | logline
xdotool search --onlyvisible --class "$SPOT01" windowkill | logline
xdotool search --onlyvisible --class "$PROC01" windowkill | logline

spot01_position_size () {
xdotool search --sync --onlyvisible --name "$SPOT01" windowunmap windowmap | logline
xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate | logline
sleep 1
echo "reset zoom...."
xdotool key --delay $kd Ctrl+0 | logline # reset zoom
sleep 1
zenity --info --title="zoom" --text="set zoom to 75%" --timeout $to
echo "set zoom to 75%...."
xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate | logline
xdotool key --delay 200 Ctrl+minus Ctrl+minus Ctrl+minus | logline # set zoom to 75%
xdotool search --sync --onlyvisible --name "$SPOT01" windowsize $BR01x $BR01y windowmove 0 -81 | logline
zenity --info --title="zoom" --text="move window...." --timeout $to
echo "move window...."
xdotool key Alt_L+space m | logline
xdotool keydown Ctrl key Left Left Left Left Left keyup Ctrl | logline
xdotool key --delay 500 Return | logline
echo "shake...."
zenity --info --title="shake" --text="shake...." --timeout $to
shake
xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate | logline
xdotool key --delay 500 Ctrl+a Ctrl+c Ctrl+f type 111 | logline
xdotool key Escape | logline
}

BR01_probe () {
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
do
if [ -z "$( xdotool search --onlyvisible --class chrome )" ]; then
		echo "there is no $BR01... exit..." | logline
		break
	else
		echo "$BR01 is opened already... enter url and set zoom to 75%..." | logline
		xdotool search --sync --onlyvisible --name "$PROC01" windowactivate | logline
		xdotool key Ctrl+l | logline
		xdotool type $SPOT01url | logline
		xdotool key Return | logline
		xdotool key --delay $kd Ctrl+0 | logline # reset zoom
		xdotool key --delay $kd Ctrl+minus Ctrl+minus Ctrl+minus | logline # set zoom to 75%
		break
fi
done
}
#BR01_probe

SPOT01_probe () {
while  [ 1 ]; do
	if [ -z "$( xdotool search --onlyvisible --name "$SPOT01" )" ]
		then
		echo "$SPOT01 non exists... open  $SPOT01 page..." | logline
		echo "$SPOT01 non exists... open  $SPOT01 page..."
		$BR01 --window-size="800,600" \
		--window-position="0,0" \
		--incognito \
		--disable-notifications \
		--mute-audio \
		--disable-device-discovery-notifications \
		--no-first-run \
		--no-default-browser-check \
		--disable-translate \
		--process-per-site \
		--disable-sync-preferences \
		--disable-gpu \
		--disable-plugins \
		--disable-plugins-discovery \
		--disable-preconnect \
		--dns-prefetch-disable \
		--no-experiments \
		--no-pings \
		--no-referrers \
		--disable-infobars \
		--disable-session-crashed-bubble \
		$SPOT01url & 2>/dev/null | logline
		BR01_probe
	else
		echo "$date Window with $SPOT01 opened successfuly...." | logline
		echo "Move and resize window...." | logline
		spot01_position_size
		break
	fi
sleep 5
done
}
SPOT01_probe
xdotool search --sync --onlyvisible --class chrome windowactivate | logline
transset -a 0.7
feh --bg-scale /opt/busy/images/wall_black_with_vertical_logo.jpg
