#!/bin/bash
#Desciption
#Script saves "friends" into sqlite local database.
#Bug: Script doesn't seve friends if the name of group is in two lines in browser.

SCRIPT=fb-save-my-friends
LOGFILE=/var/log/busy4me.log
#config file
source /opt/busy4me/fb/fb-config


logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $USER $SCRIPT - $line" | tee -a $LOGFILE 
    done
}

xdotool search --class zenity windowkill

login=$(cat "$login_source")
echo 'login =' $login | logline
login_string=$login
login_string=$(echo $login_string | tr '@.' '_')
echo 'login_string =' $login_string | logline
user_db="/opt/busy/fb/db/fb_$login_string.db"
echo 'Use database:' $user_db | logline

profile_id=""
profile_name="me"

SPOT01="facebook" # spot 01
SPOT01url="https://facebook.com" # url 01
login=fblogin@mail.com
password=fbpassword
login_url=http://m.facebook.com
fb_friends_url="https://www.facebook.com/friends"

my_friends_url="$SPOT01url/$profile_name/friends"
about_url="$SPOT01url/$profile_name/about"
profile_url="$SPOT01url/$profile_name"

feh --bg-scale /opt/busy/images/wall_black_with_vertical_logo.jpg | logline
xdotool search --onlyvisible --name Settings windowkill

# go to my friends
xdotool search --onlyvisible --class chrome windowactivate
transset -a 0.8
xdotool key --delay $kdl Escape Ctrl+l && xdotool type --delay $kd $my_friends_url && xdotool key --delay $kdl Return
transset -a 0.7
(sleep 2 && wmctrl -F -a "page_probe" -b add,above) & zenity --info --title="page_probe" --text="Open $my_friends_url" --timeout 5
sleep 1
xdotool search --onlyvisible --class chrome windowactivate
mark00="All Friends"
mark01="All friends"

my_friends_url_probe () {
for i in {1..20} ; do
	xdotool search --onlyvisible --class chrome windowactivate
	echo -e "\e[90m my_friends_url_probe...\e[0m" | logline
	xclip -selection clipboard /opt/busy/files/blank
	xdotool key --delay $kds Ctrl+a Ctrl+c Ctrl+Shift+a
	clip=$( xclip -out -selection clipboard )
	echo -e "\e[30m\e[43m|---   START clip   --->\e[100m\e[30m"$clip"\e[30m\e[43m<---   END clip   ---|\e[0m" | logline
		case "$clip" in
		*"$mark00"*)
			echo -e "\e[32m I see friends...\e[0m mark00=$mark00" | logline
			break
		;;
		*"$mark01"*)
			echo -e "\e[32m I see friends...\e[0m mark01=$mark01" | logline
			break
		;;
		*)
			echo -e "\e[90m mark01=$mark01 \e[0m Can't see friends... try again..." | logline
			page_error=$((page_error+1))
			if [ $page_error -ge 19 ]; then
				echo "\e[41m\e[30m...\e[0m\e[31m Page error, break script...\e[0m" | logline
				exit 1
			fi
		;;
		esac
	done
}

my_friends_url_probe
(sleep 2 && wmctrl -F -a "save_my_friends" -b add,above) & zenity --info --title="save_my_friends" --text="save my friends to local database..." --timeout 8 &
sleep 1
#zenity --info --title="Activate chrome" --text="search --onlyvisible --class chrome windowactivate" --timeout $to
xdotool search --onlyvisible --class chrome windowactivate
#my_friends_url_probe

mark02="More about you"
mark02_i=0
mark03="friends_tab"
mark04="Leave Group"
mark05="#"
mark06="reviews"
mark07="reviews_written"

save_my_friends () {
iter=5
for (( i=1; i<$iter; i++ )); do
    echo "# Pick friends up... step $i"
    echo "$(( (i * 100) /$iter ))"
    sleep 0.5
    shift 1
done | zenity --progress --title="Pick friends up..." --percentage=0 --no-cancel --auto-close
	echo "save_my_friends start..."
	xdotool search --onlyvisible --class chrome windowactivate
zenity --info --title="save_my_friends" --text="xdotool key --delay $kdl Tab Tab Tab Tab" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kdl Tab Tab Tab Tab
    sleep 0.5
zenity --info --title="save_my_friends" --text="xdotool key --delay $kdl Ctrl+f" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kdl Ctrl+f | logline
	xdotool type --delay $kdl "$mark01" | logline
    sleep 0.5
zenity --info --title="save_my_friends" --text="xdotool key --delay $kdl Escape" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kdl Escape | logline
	echo "Tab...."
    sleep 0.5
zenity --info --title="save_my_friends" --text="xdotool key --delay $kd Tab" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kd Tab Tab Tab Tab Tab Tab Tab
    sleep 0.5

# set start position
# the position is determined by the number of links on the friends page, how many URL's was found last time
last_position=$(sqlite3 $user_db "SELECT position FROM fb_friends ORDER BY position DESC LIMIT 1;")
last_url=$(sqlite3 $user_db "SELECT id FROM fb_friends ORDER BY position DESC LIMIT 1;")
echo -e "\e[30m\e[36m position -> \e[0m\e[36m last_position=\e[95m$last_position \e[36m ... go to the last position ..." | logline
for (( tab_count=1; tab_count<$last_position; tab_count++ )); do
	xdotool key --delay $kd Tab
done
	xdotool key --delay $kd Shift+Tab Shift+Tab Shift+Tab Shift+Tab Shift+Tab

position=$last_position
valid_URL_counter=$last_url
	
mark06_i=0
#while (( mark06_i == 0 || not_valid_counter_1 < 10 || not_valid_counter_2 < 10 ))
while (( mark06_i == 0 ))
do
	position=$((position+1))
	/bin/bash /opt/busy4me/busy SYSTEM --clip-clear
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key Escape Tab Tab Tab Tab Shift+Tab Shift+Tab Shift+Tab Shift+Tab
	xdotool key --delay $kd Tab
	xdotool key --delay $kd Shift+F10
	sleep 0.2
	#	xclip -selection clipboard /opt/busy/files/blank
	xdotool key --delay $kd e
	sleep 0.2
	#kill 'settings' window if open, this opening from content menu when Teb goes to Chrome 'top'
	#Shift+F10 (content menu) +e - is opening 'Edit engine settings'
	# so we kill settings window
	#To do: script with 'wmctrl' command to prevent opening other windows..

	settings_window=$(wmctrl -l | grep -i settings | awk '{print $1}')
	if ! [ -z $settings_window ]
		then
			echo "...kill chrome settings window" | logline
			wmctrl -i -c $(wmctrl -l | grep -i settings | awk '{print $1}')
	fi
	clip1=$( xclip -out -selection clipboard )
		case "$clip1" in
			*$mark05*)
		#		zenity --info --title="clipboard" --text="This is not valid URL \n $clip1 \nNext..." --timeout $tos > /dev/null 2>&1
				not_valid_counter_1=$((not_valid_counter_1+1))
				if [ $not_valid_counter_1 -ge 6 ]; then
					echo -e "\e[41m break -> \e[0m\e[31m not valid user URL $not_valid_counter_1 times, exit script..." | logline
					break
				fi
			;;
			*$mark03*)
		#		zenity --info --title="clipboard" --text="user URL OK: \n $clip1" --timeout $tos > /dev/null 2>&1
				valid_URL_counter=$((valid_URL_counter+1))
				not_valid_counter_1=0
				not_valid_counter_2=0
				kd=400
				clip1=$(sed 's/https:\/\/www.facebook.com/fb.com/' <<< "$clip1") # replace long url with short one
				clip1=$(sed 's/&fref=pb&hc_location=friends_tab//' <<< "$clip1") # trim some strings
				clip1=$(sed 's/\?fref=pb&hc_location=friends_tab//' <<< "$clip1") # trim some strings
				clip_display=$(sed 's/fb.com/\*\*.com/' <<< "$clip1") # replace strings for display in console
				clip_display=$(sed 's/fb.com/\*\*\*/' <<< "$clip_display") # replace strings for display in console
				echo -e "valid_URL_counter=$valid_URL_counter \e[104m\e[30m url -> \e[0m\e[33m $clip_display \e[0m\e[94m position=$position \e[0m\e[90m sql -> INSERT INTO fb_friends...\e[0m" | logline
					sqlite3 $user_db "INSERT INTO fb_friends (name,url,date,DateId,label,position,stat1,stat2)
					VALUES (
					'friend',
					'$clip1',
					DateTime('now'),
					'insert',
					'fb-save-my-friends',
					'$position',
					'0',
					'0'
					);"
		#		sqlite3 user_db "insert into fb_friends (f,l) values ('john','smith');"
			;;
			*)
		#		zenity --info --title="clipboard" --text="What is it?: \n $clip1" --timeout $tos > /dev/null 2>&1
				not_valid_counter_2=$((not_valid_counter_2+1))
				if [ $not_valid_counter_2 -ge 3 ]; then
					xdotool key --delay $kdl Page_Down Page_Up
				fi
				if [ $not_valid_counter_2 -ge 10 ]; then
					echo -e "\e[41m break -> \e[0m\e[31m not valid user URL $not_valid_counter_2 times, break script... \e[0m " | logline
					kd=200
					break
				fi
				kd=500
				echo -e "\e[90m This is not valid user URL... not_valid_counter_2=$not_valid_counter_2 not_valid_counter_1=$not_valid_counter_1\e[0m"
			;;
			*$mark06*)
		#		zenity --info --title="clipboard" --text="This the end of friends page... exit..." --timeout $tol > /dev/null 2>&1
				echo -e "\e[105m\e[30m This the end of friends page...\e[33m mark06=$mark06 \e[0m exit... " | logline
				mark06_i=1
				break
			;;
			*$mark07*)
		#		zenity --info --title="clipboard" --text="This the end of friends page... exit..." --timeout $tol > /dev/null 2>&1
				echo -e "\e[105m\e[30m This the end of friends page...\e[33m mark07=$mark07 \e[0m exit..." | logline
				mark06_i=1
				break
			;;
		esac
done
}

	zenity --info --title="Function" --text="xdotool search --onlyvisible --class chrome windowactivate.... and Function save_my_friends" --timeout $to
xdotool search --onlyvisible --class chrome windowactivate --timeout $to
save_my_friends

echo -e "\e[33m Saved \e[43m\e[30m $valid_URL_counter \e[0m\e[33mfriends ...\e[0m" | logline
(sleep 1 && wmctrl -F -a "valid_URL_counter" -b add,above) & zenity --info --title="valid_URL_counter" --text="Saved $valid_URL_counter friends..." --timeout $tol

scroll_to_end () {
echo "Start scrolling to the end..."
xdotool search --onlyvisible --class chrome windowactivate
echo "Set transparent... 0.7"
transset -a 0.7
echo "mark02 = $mark02"
echo "mark02_i = $mark02_i"

while [ $mark02_i -eq 0 ]
do
	echo "Scroll page down..." | logline
	xdotool key --delay $kds Page_Down
	xclip -selection clipboard /opt/busy/files/blank
	sleep 0.5
	xdotool key --delay $kds Ctrl+a Ctrl+c Ctrl+Shift+a
	clip=$( xclip -out -selection clipboard )
		case "$clip" in
		*$mark02*)
		echo "This is the end of page? I see $mark02"
			xdotool key --delay $kds Page_Down
			mark02_i=1
		;;
		*)
		echo "Scroll again...."
		;;
		esac
	echo "# Looking for end mark02......... "
done
}

#scroll_to_end

echo "$count01"

echo "Stop scrolling...."
#close Settings window (I do not know why is opening every time)
#xdotool search --onlyvisible --name Settings windowkill

transset -a 0.7
echo "stop $SCRIPT" | logline

