#!/bin/bash
# Update all files
PROJECT="busy4me"
#export PATH=$PATH:/opt/$PROJECT
BUSYUSER="busyman"

mkdir /opt/$PROJECT 2>/dev/null
mkdir /tmp/$PROJECT-tmp 2>/dev/null
cd /opt/$PROJECT

# update root and user bash preference files
rm /root/.bash_aliases
rm /root/.bashrc
rm -rf /home/$BUSYUSER/.bash_aliases
rm -rf /home/$BUSYUSER/.bashrc
echo -e "Download bash preferences files ... \n\ curl -L -k https://busy4.me/node/opt/busy4me/*"
	curl -L -k https://busy4.me/node/root/.bash_aliases -o /root/.bash_aliases
	curl -L -k https://busy4.me/node/root/.bashrc -o /root/.bashrc
	curl -L -k https://busy4.me/node/home/busyman/.bash_aliases -o /home/busyman/.bash_aliases
	curl -L -k https://busy4.me/node/home/busyman/.bashrc -o /home/busyman/.bashrc

# create backup in tmp
TMP_DIR="/tmp/$PROJECT-tmp/$(date +%Y-%m-%d--%H-%M-%S)"
mkdir $TMP_DIR
cp -R /opt/$PROJECT/* $TMP_DIR

# remove all project files	
rm -rf /opt/$PROJECT/*

echo "Clean google-chrome busyman data..."
	rm -rf /home/$BUSYUSER/.config/google-chrome/Default
	rm -rf /home/$BUSYUSER/.cache/google-chrome
	rm -rf /home/$BUSYUSER/.config/google-chrome/Singleton*

echo "Download new files... \n\ curl -L -k https://busy4.me/node/opt/busy4me/*"
	curl -L -k https://busy4.me/node/opt/busy4me/update -o /opt/busy4me/update
	curl -L -k https://busy4.me/node/opt/busy4me/update2 -o /opt/busy4me/update2
	curl -L -k https://busy4.me/node/opt/busy4me/config -o /opt/busy4me/config
	curl -L -k https://busy4.me/node/opt/busy4me/frame01 -o /opt/busy4me/frame01
	curl -L -k https://busy4.me/node/opt/busy4me/windows-init -o /opt/busy4me/windows-init
	curl -L -k https://busy4.me/node/opt/busy4me/windows-normal -o /opt/busy4me/windows-normal
	curl -L -k https://busy4.me/node/opt/busy4me/chrome-init -o /opt/busy4me/chrome-init
	curl -L -k https://busy4.me/node/opt/busy4me/menu-init -o /opt/busy4me/menu-init
	curl -L -k https://busy4.me/node/opt/busy4me/mouse-01 -o /busy4me/mouse-01
	curl -L -k https://busy4.me/node/opt/busy4me/xterm-transparent -o /busy4me/xterm-transparent
	curl -L -k https://busy4.me/node/opt/busy4me/zenity -o /opt/busy4me/zenity
	curl -L -k https://busy4.me/node/opt/busy4me/compare_logs_reboot.sh -o /opt/busy4me/compare_logs_reboot.sh
	curl -L -k https://busy4.me/node/opt/busy4me/change_hostname.sh -o /opt/busy4me/change_hostname.sh
	curl -L -k https://busy4.me/node/opt/busy4me/change_hostname_uuid.sh -o /opt/busy4me/change_hostname_uuid.sh
	curl -L -k https://busy4.me/node/opt/busy4me/stream_to_twitch.sh -o /opt/busy4me/stream_to_twitch.sh
	curl -L -k https://busy4.me/node/opt/busy4me/windows-check.sh -o /opt/busy4me/windows-check.sh
	curl -L -k https://busy4.me/node/opt/busy4me/windows-uneeded-close.sh -o /opt/busy4me/windows-uneeded-close.sh
	curl -L -k https://busy4.me/var/www/html/index.html -o /var/www/html/index.html

	mkdir /opt/$PROJECT/fb
	cd /opt/$PROJECT/fb
	rm -rf /opt/$PROJECT/fb/*
	mkdir /opt/$PROJECT/fb/img
	curl -L -k https://busy4.me/node/opt/busy4me/fb/img/chat_icon.png -o /opt/$PROJECT/fb/img/chat_icon.png
	curl -L -k https://busy4.me/node/opt/busy4me/fb/img/cross_chat.png -o /opt/$PROJECT/fb/img/cross_chat.png
	curl -L -k https://busy4.me/node/opt/busy4me/fb/img/cross_chat2.png -o /opt/$PROJECT/fb/img/cross_chat2.png
	curl -L -k https://busy4.me/node/opt/busy4me/fb/img/cross_chat3.png -o /opt/$PROJECT/fb/img/cross_chat3.png
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-walking-around -o /opt/busy4me/fb/fb-walking-around
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-open -o /opt/busy4me/fb/fb-open
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-init -o /opt/busy4me/fb/fb-init
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-init -o /opt/busy4me/fb/fb-init-99
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-config -o /opt/busy4me/fb/fb-config
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-login -o /opt/busy4me/fb/fb-login
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-login -o /opt/busy4me/fb/fb-login
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-scroll -o /opt/busy4me/fb/fb-scroll
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-like-random-fanpages -o /opt/busy4me/fb/fb-like-random-fanpages
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-save-my-groups -o /opt/busy4me/fb/fb-save-my-groups
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-save-my-friends -o /opt/busy4me/fb/fb-save-my-friends
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-collect-data -o /opt/busy4me/fb/fb-collect-data
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-update-my-groups-01-o /opt/busy4me/fb/fb-update-my-groups-01
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-update-posted-links.py -o /opt/busy4me/fb/fb-update-posted-links.py
	curl -L -k https://busy4.me/node/opt/busy4me/fb/mouse-position.py -o /opt/busy4me/fb/mouse-position.py
	curl -L -k https://busy4.me/node/opt/busy4me/fb/mouse-move-around.py -o /opt/busy4me/fb/mouse-move-around.py
	curl -L -k https://busy4.me/node/opt/busy4me/fb/mouse-move-01.py -o /opt/busy4me/fb/mouse-move-01.py
	curl -L -k https://busy4.me/node/opt/busy4me/fb/mouse-move-02.py -o /opt/busy4me/fb/mouse-move-02.py
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-chat-close-windows.py -o /opt/busy4me/fb/fb-chat-close-windows.py
	curl -L -k https://busy4.me/node/opt/busy4me/fb/fb-chat-detect-activity.py -o /opt/busy4me/fb/fb-chat-detect-activity.py
	chmod +x /opt/$PROJECT/*
	chmod +x /opt/$PROJECT/*.*
	chmod +x /opt/$PROJECT/fb/*

echo "Create symlinks for logs..."
	mkdir /opt/$PROJECT/log
	ln -s /var/log/busy4me.log /node/opt/busy4me/busy4me.log
	ln -s /var/log/busy4me_cron.log /node/opt/busy4me/busy4me_cron.log

echo "All files updated .............................................."
echo "ls -la /opt/$PROJECT"
	ls --color -lAGbh --time-style='+%b %d %Y %H:%M' /opt/$PROJECT
echo "ls -la /opt/$PROJECT"/fb
	ls --color -lAGbh --time-style='+%b %d %Y %H:%M' /opt/$PROJECT/fb
echo "ls -la /var/www/html"
	ls --color -lAGbh --time-style='+%b %d %Y %H:%M' /var/www/html

	chmod 777 /var/log/busy4me.log

echo "OK"
