#!/bin/bash
PROJECT="busyman"
PLUGIN="yo"
SCRIPT="yo-init"
SPOT_NAME="youtube"
SPOT_URL="https://youtube.com"
LOGFILE=/var/log/${PROJECT}.log
SAVE_DIR=/opt/${PROJECT}/plugins/${PLUGIN}/data # with user permision 777
PROJECT_DIR=/opt/${PROJECT}/plugins/${PLUGIN} # with root permision 755, read only for users
echo "start" > ${SAVE_DIR}/${SCRIPT}${DISPLAY}-status
mkdir -p $SAVE_DIR 2>/dev/null

__wallpaper_change () {
  INT=$(( $INT +1 ))
  if [ $INT -eq 4 ]; then
    INT=0
  fi
feh --bg-scale /opt/${PROJECT}/data/images/wall0$INT.png
}

logline() {
  __wallpaper_change
    while IFS= read -r line; do
      echo -e "$(date +%F' '%T) $USER $SCRIPT - $line\e[0m" | tee -a $LOGFILE
    done
}

source /opt/${PROJECT}/${PROJECT}.sh # global functions
if ! source /opt/${PROJECT}/${PROJECT}.cfg; then
  echo "There is no config file!... stop." | logline; exit 1
fi

echo -e "\e[95m$(date +%F' '%T) $USER $SCRIPT start.............................................." | logline
echo -e "start..." | logline

if [ $USER = "root" ]; then
  echo "Do not run as root! exit..." | logline
  exit
fi

# Clean google-chrome busyman data... just in case...
echo -e "\e[91m *F:_clean_data, clean google-chrome busyman data...\e[0m" | logline
  rm -rf /home/$BUSYUSER/.config/google-chrome/Default
  rm -rf /home/$BUSYUSER/.cache/google-chrome
  rm -rf /home/$BUSYUSER/.config/google-chrome/Singleton*

__TRANSSET=0                                         ############################################################
transset_blank () {                                  #  change __TRANSSET to 0 to set current window invisible  #
  transset -a $__TRANSSET                            ############################################################
}

xdotool mousemove 45 45
echo "... * kill existing windows: BR01=$BR01 SPOT_NAME=$SPOT_NAME PROC01=$PROC01..." | logline
xdotool search --onlyvisible --class "$BR01" windowkill | logline
xdotool search --onlyvisible --class "$SPOT_NAME" windowkill | logline
xdotool search --onlyvisible --class "$PROC01" windowkill | logline

SPOT_NAME_position_size() {
  _WINDOW=$(xdotool search --onlyvisible --name "$SPOT_NAME")
  echo -e "\e[96m *F:SPOT_NAME_position_size, move and resize window... _WINDOW=\e[0m$_WINDOW" | logline
  xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowunmap windowmap| logline
  transset_blank
  xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowactivate | logline
  transset_blank
  for i in {1..10} ; do
    __wallpaper_change
    sleep 0.1
  done
  __wallpaper_change
  echo "reset zoom...."
  xdotool key --delay $kd Ctrl+0 | logline # reset zoom
  for i in {1..10} ; do
    __wallpaper_change
    sleep 0.1
  done
  transset_blank
  # zenity --info --title="zoom" --text="set zoom to 75%" --timeout $to
  __wallpaper_change
  echo "set zoom to 75%...."
  xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowactivate | logline
  # xdotool key --delay 200 Ctrl+minus Ctrl+minus Ctrl+minus | logline # set zoom to 75%
  xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowsize $BR01x $BR01y windowmove $POSITION_x $POSITION_y | logline
  transset_blank
  # zenity --info --title="zoom" --text="move window...." --timeout $to
  __wallpaper_change
  #echo "move window 5 steps below x=0...."
  #xdotool key Alt_L+space m | logline
  #xdotool keydown Ctrl key Left Left Left Left Left keyup Ctrl | logline
  #xdotool key --delay 500 Return | logline
  #xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowunmap windowmap | logline
  xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowactivate | logline
  # unhide browser window
  wmctrl -i -r $(wmctrl -l | grep -i $_SPLASH | awk '{print $1}') -b add,below
  pkill xli
  feh --bg-scale /opt/${PROJECT}/data/images/wall-blue.png
  transset -a 0.1; sleep 0.1
  transset -a 0.2; sleep 0.1
  transset -a 0.3; sleep 0.1
  transset -a 0.4; sleep 0.1
  transset -a 0.5; sleep 0.1
  transset -a 0.6; sleep 0.1
  transset -a 0.7; sleep 0.1
  transset -a 0.8; sleep 0.1
  transset -a 0.9; sleep 0.1
  transset -a 1
  # set fullscreen image below and kill it
  echo "shake...."
  # zenity --info --title="shake" --text="shake...." --timeout $to
  shake
  hide_window
  xdotool search --sync --onlyvisible --name "$SPOT_NAME" windowactivate | logline
  xdotool key --delay 500 Ctrl+f type ${SPOT_NAME} | logline
  xdotool key Escape | logline
}

BR01_probe() {
echo -e "\e[96m *F:BR01_probe, check \"$BR01\" window\e[0m" | logline
if [ -z "$( xdotool search --onlyvisible --class google-chrome )" ]; then
		echo "there is no \"$BR01\"... exit..." | logline
	else
		echo "\"$BR01\" is opened already... enter url and set zoom to 75%..." | logline
		xdotool search --sync --onlyvisible --name "$PROC01" windowactivate | logline
		xdotool key Ctrl+l | logline
		xdotool type $SPOT_URL | logline
		xdotool key Return | logline
		xdotool key --delay $kd Ctrl+0 | logline # reset zoom
		# xdotool key --delay $kd Ctrl+minus Ctrl+minus Ctrl+minus | logline # set zoom to 75%
    for i in {1..50} ; do
      __wallpaper_change
      sleep 0.1
    done
fi
}

SPOT_NAME_probe() {
  echo -e "\e[96m *F:SPOT_NAME_probe, check \"$SPOT_NAME\" window\e[0m" | logline
while  [ 1 ]; do
	if [ -z "$( xdotool search --onlyvisible --name "$SPOT_NAME" )" ]; then
    echo "$SPOT_NAME non exists... open  $SPOT_NAME page..." | logline
    echo "$SPOT_NAME non exists... open  $SPOT_NAME page..."
    BR01_run
    BR01_probe
	else
		echo "$date Window with $SPOT_NAME opened successfuly...." | logline
		echo "Move and resize window...." | logline
		SPOT_NAME_position_size
		break
	fi
  for i in {1..50} ; do
    __wallpaper_change
    sleep 0.1
  done
done
}

BR01_run() {
  $BR01 --window-size="900,768" \
  --window-position="140,0" \
  --incognito \
  --disable-notifications \
  --mute-audio \
  --disable-device-discovery-notifications \
  --no-first-run \
  --no-default-browser-check \
  --disable-translate \
  --process-per-site \
  --disable-sync-preferences \
  --disable-gpu \
  --disable-plugins \
  --disable-plugins-discovery \
  --disable-preconnect \
  --dns-prefetch-disable \
  --no-experiments \
  --no-pings \
  --no-referrers \
  --disable-infobars \
  --disable-session-crashed-bubble \
  $SPOT_URL & 2>/dev/null | logline
}

echo -e "\e[96m *F:BR01_run, first run \"$BR01\" \e[0m" | logline
feh --bg-scale /opt/${PROJECT}/data/images/wall00.png
BR01_run
for i in {1..20} ; do
  xdotool search --sync --onlyvisible --class chrome windowactivate | logline
  transset_blank
  #  __wallpaper_change
  sleep 0.25 | logline
done
for i in {1..50} ; do
  __wallpaper_change
  sleep 0.1
done
transset_blank
SPOT_NAME_probe
xdotool search --sync --onlyvisible --class chrome windowactivate | logline
transset -a 0.9
feh --bg-scale /opt/${PROJECT}/data/images/wall_black_with_vertical_logo.jpg
while  [ 1 ]; do
  echo "done" > ${SAVE_DIR}/${SCRIPT}${DISPLAY}-status
  sleep 86400 # sleep 1 day
done
