#!/bin/bash
# Setup busy4.me in user "busyman" home directory
# Install dependencies
# X (the display server)
# openbox as Windows Manager
# google-chrome Google Chrome as www browser
#export PATH=$PATH:/root
SCRIPT=init-1
LOGFILE=/var/log/busy4me.log
chmod 777 /var/log/busy4me.log

# logrotate
# add tesk to logrotate
# rotate logs daily, was problem with compare logs when log is a big file
echo -e "\e[44m ................... update logrotate \e[0m"
rm /etc/logrotate.d/busy4me 2>/dev/null
mkdir /var/log/busy4me 2>/dev/null
cat > /etc/logrotate/busy4me << EOF
/var/log/busy4me.log
{
        rotate 7
        size 1M
        missingok
        dateext
        copytruncate
		olddir /var/log/busy4me
}

EOF

# add user and group "busyman" and 'admin"
ADMIN_USER=admin
BUSYUSER=busyman

logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $SCRIPT - $line" | tee -a $LOGFILE 
    done
}
echo "$(date +%F' '%T) $SCRIPT - Start init-1 script ..." | logline

if [ $USER != "root" ]
	then
		echo -e "\e[31mRun this script as root! exit...\e[0m"
		echo "Run this script as root! exit..." | logline
		exit 1
	else
		echo -e "\e[32mRun OK as root...\e[0m" | logline
fi

groupadd $ADMIN_USER >> $LOGFILE
useradd $ADMIN_USER -s /bin/bash -m -g $ADMIN_USER | logline
groupadd busyman >> $LOGFILE
useradd busyman -s /bin/bash -m -g busyman | logline
# add directory for write any files by users, chmod 777
# don't want to see any files in busyman directory, 
# sometime it's seen on the screen when somehow open file dialog apears
# in chrome Ctrl+o

# create directory with access for users
mkdir /opt/busy 2>/dev/null
chmod 777 /opt/busy
mkdir /opt/busy/{files,images,sounds,videos} 2>/dev/null
chmod 777 /opt/busy/{files,images,sounds,videos}
# empty file for blank clipboard
# touch /opt/busy/files/blank

# add file .bash_aliases to user account
cat > /home/busyman/.bash_aliases << EOF
# Command aliases for busyman
alias ls="ls --color -lAGbh --time-style='+%b %d %Y %H:%M'"
EOF

# add file .bash_aliases to root account
cat > /root/.bash_aliases << EOF
# Command aliases for root
alias ls="ls --color -lAGbh --time-style='+%b %d %Y %H:%M'"
EOF

echo -e "\e[31m Remove init-0 file..................... \e[0m" >> $LOGFILE
rm /root/init-0 >> $LOGFILE

lsb_release -a | logline
uname -a | logline

# install X, browser, and other packages
# apt-get update && apt-get install -y software-properties-common python-software-properties
echo -e "\e[100m Install software-properties-common ... \e[0m" | logline
apt-get install -y software-properties-common | logline # for Debian
echo -e "\e[100m Install wget curl ... \e[0m" | logline
apt-get install -y wget curl | logline
wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - | logline
# zmiany dla Ubuntu
add-apt-repository 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | logline
# sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
apt-get update | logline >> $LOGFILE
echo -e "\e[100m Install xorg ... \e[0m" | logline
# zmiany dla Ubuntu
# apt-get install -y -V --no-install-recommends xserver-xorg xserver-xorg-core xserver-xorg-input-all xserver-xorg-input-evdev xserver-xorg-input-vmmouse xserver-xorg-input-synaptics xorg-input-abi-21 xserver-xorg-input-mouse xorg | logline >> $LOGFILE
apt-get install -y -V --no-install-recommends xorg | logline >> $LOGFILE
apt-get install -y -V --no-install-recommends --allow-unauthenticated xinit | logline >> $LOGFILE # without lightdm for now
echo -e "\e[100m Install openbox google-chrome-stable ... \e[0m" | logline
apt-get install -y --no-install-recommends openbox google-chrome-stable | logline
echo -e "\e[100m Install xdotool wmctrl xcompmgr feh nginx bc ntp zenity xclip ntpdate scrot screen sqlite3 Xvfb ... \e[0m" | logline
apt-get install -y xdotool wmctrl xcompmgr feh nginx bc ntp zenity xclip ntpdate scrot screen sqlite3 tint2 | logline >> $LOGFILE
apt-get install -y xvfb --fix-missing | logline
# apt-get install -y Xvfb | logline >> $LOGFILE # not found in Ubuntu

#hostnamectl seems to need dbus, hostnamectl used for change hostname
echo -e "\e[100m Install dbus ... \e[0m" | logline
apt-get install -y dbus | logline >> $LOGFILE

# change hostname to unique name, pattern: busy-UUID
echo -e "\e[100m Change hostname maching to product_uuid... \e[0m" | logline
old_hostname=$(cat /etc/hostname)
new_hostname=busy-$(cat /sys/class/dmi/id/product_uuid)
hostnamectl set-hostname "$new_hostname"
echo -e "\e[36m   ......update /etc/hosts file \e[0m"
cp /etc/hosts /etc/hosts.bak
sed -i "/\s$old_hostname/d" /etc/hosts
echo "127.0.1.1 $new_hostname" >> /etc/hosts

sysctl vm.swappiness=10
# set swappiness permamently
echo "vm.swappiness = 10" >> /etc/sysctl.conf


# backorts need for install salt-common which can't be installed without python-systemd
echo 'deb http://deb.debian.org/debian jessie-backports main' >> /etc/apt/sources.list

#add main repo & install SaltStack 
echo -e "\e[100m Saltstack install Start ... \e[0m" | logline
rm /etc/apt/sources.list.d/saltstack.list 2>/dev/null | logline
# echo 'deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main' >> /etc/apt/sources.list.d/saltstack.list | logline
echo 'deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main' >> /etc/apt/sources.list.d/saltstack.list | logline
echo -e "\e[100m repo Saltstack certificate ... \e[0m" | logline
wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add - | logline
# wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add - | logline
apt-get update
apt-get install -y salt-common salt-minion
rm /etc/salt/minion
cat > /etc/salt/minion  << EOF
master: 192.168.121.155
EOF
echo -e "\e[100m Saltstack install End ... \e[0m" | logline

# install ffmpeg ffplay for streaming desktop
echo -e "\e[100m Install ffmpeg... \e[0m" | logline
rm /etc/apt/sources.list.d/deb-multimedia.list 2>/dev/null
cat > /etc/apt/sources.list.d/deb-multimedia.list  << EOF
deb https://notesalexp.org/debian/xenial/ xenial main
EOF
apt-get install apt-transport-https
apt-get update -oAcquire::AllowInsecureRepositories=true
apt-get  -y --force-yes install notesalexp-keyring -oAcquire::AllowInsecureRepositories=true
apt-get update #to update package list

apt-get install -y build-essential libmp3lame-dev libvorbis-dev libtheora-dev libspeex-dev yasm pkg-config libfaac-dev libopenjpeg-dev libx264-dev
apt-get install -y libav-tools
echo -e '\e[36m ffmpeg installed ..................... \e[0m' | logline
# ffmpeg installed

echo 'Download local webservice menu file.....................' | logline
wget -nv --no-check-certificate https://busy4.me/var/www/html/index.html -O /var/www/html/index.html | logline

echo -e "\e[33m Change autostart startx in user busyman .profile file.........................\e[0m" | logline
#sed -i 's/date/startx/g' /home/busyman/.profile | logline

# run X in tty1 (after autologin)
rm /home/$BUSYUSER/.profile
cat > /home/$BUSYUSER/.profile  << 'EOF'
[[ $(tty) = /dev/tty1 ]] && setterm -blank 0 -powersave off && startx
EOF
chown $BUSYUSER:$BUSYUSER /home/busyman/.profile | logline

# download big files
wget -nv --no-check-certificate https://busy4.me/node/opt/busy/images/wallpaper.jpg -O /opt/busy/images/wallpaper.jpg | logline
wget -nv --no-check-certificate https://busy4.me/node/opt/busy/images/wall_black_with_vertical_logo.jpg -O /opt/busy/images/wall_black_with_vertical_logo.jpg | logline
feh --bg-scale /opt/busy/images/wallpaper.jpg | logline

#echo 'Run google-chrome.sh script.....................'
rm -R /home/busyman/.config/openbox/ | logline
mkdir -pv /home/busyman/.config/openbox/ | logline
echo -e "\e[36m Copy openbox config files.....................\e[0m" | logline
cp -R /etc/xdg/openbox /home/busyman/.config | logline
chown -R busyman:busyman /home/busyman/.config | logline

rm -R /home/busyman/.config/openbox/autostart | logline
cat > /home/busyman/.config/openbox/autostart << EOF
# Programs that will run after Openbox windows manager has started
xrandr --output default --mode 800x600 &&
xrandr --output Virtual1 --mode 800x600 &&
xrandr --output VGA-1 --mode 800x600 &&
feh --bg-scale /opt/busy/images/wallpaper.jpg &&
xset -dpms &&
xset s off &&
xcompmgr &
/opt/busy4me/frame00 &
EOF

# for desktop/server PC name "VGA-1", add new mode first
# tested on HP C7000, double blade L620c G7, Xeon E7-2820
cvt 1280 1024 60
xrandr --newmode "1280x1024_60.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync
xrandr -q
xrandr --addmode VGA-1 1280x1024_60.00
xrandr --output VGA-1 --mode 1280x1024_60.00

cvt 1152 864 60
xrandr --newmode  "1152x864_60.00"   81.75  1152 1216 1336 1520  864 867 871 897 -hsync +vsync
xrandr --addmode VGA-1 1152x864_60.00
xrandr --output VGA-1 --mode 1152x864_60.00

cvt 1440 900 60
xrandr --newmode "1440x900_60.00"  106.50  1440 1528 1672 1904  900 903 909 934 -hsync +vsync
xrandr --addmode VGA-1 1440x900_60.00
xrandr --output VGA-1 --mode 1440x900_60.00

cvt 1600 900 60
xrandr --newmode "1600x900_60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync
xrandr --addmode VGA-1 1600x900_60.00
xrandr --output VGA-1 --mode 1600x900_60.00

cvt 1920 1080 60
xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode VGA-1 1920x1080_60.00
xrandr --output VGA-1 --mode 1920x1080_60.00

cvt 1920 1200 60
xrandr --newmode "1920x1200_60.00"  193.25  1920 2056 2256 2592  1200 1203 1209 1245 -hsync +vsync
xrandr --addmode VGA-1 1920x1200_60.00
xrandr --output VGA-1 --mode 1920x1200_60.00

# change resolution at start
rm cat > /home/busyman/.xprofile
cat > /home/busyman/.xprofile << EOF
xrandr --newmode "1600x900_60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync
xrandr --addmode VGA-1 1600x900_60.00
xrandr --output VGA-1 --mode 1600x900_60.00
EOF
chown busyman:busyman /home/busyman/.xprofile

cvt 1920 1200 60
cvt 1920 1080 60

cat > /home/busyman/.config/openbox/autostart << EOF
# Programs that will run after Openbox windows manager has started
xrandr --output VGA-1 --mode 1280x1024 &&
feh --bg-scale /opt/busy/images/wallpaper.jpg &&
xset -dpms &&
xset s off &&
xcompmgr &
/opt/busy4me/frame00 &
EOF

cat > /home/busyman/.config/openbox/autostart << EOF
# Programs that will run after Openbox windows manager has started
xrandr --output default --mode 800x600 &&
feh --bg-scale /opt/busy/images/wallpaper.jpg &&
xset -dpms &&
xset s off &&
xcompmgr &
/opt/busy4me/frame00 &
EOF

chown busyman:busyman /home/busyman/.config/openbox/*
chmod +x /home/busyman/.config/openbox/autostart | logline

cat > /usr/share/xsessions/busyman.desktop << EOF
[Desktop Entry]
Version=1.0
Name=busyman
Exec=default
Icon=
Type=Application
EOF

# download or update particular service (in this case project "busy4me")
PROJECT="busy4me"
rm -Rf /opt/$PROJECT
mkdir /opt/$PROJECT
mkdir /opt/$PROJECT/log
ln -s /var/log/busy4me.log /opt/busy4me/busy4me.log
export PATH=$PATH:/opt/$PROJECT
cd /opt/$PROJECT
echo "wget -q --no-check-certificate https://busy4.me/node/opt/busy4me/*"
wget -nv --no-check-certificate https://busy4.me/node/opt/busy4me/update -O /opt/busy4me/update | logline
wget -nv --no-check-certificate https://busy4.me/node/opt/busy4me/config -O /opt/busy4me/config | logline
wget -nv --no-check-certificate https://busy4.me/node/opt/busy4me/windows-init -O /opt/busy4me/windows-init | logline
wget -nv --no-check-certificate https://busy4.me/node/opt/busy4me/chrome-init -O /opt/busy4me/chrome-init | logline
wget -nv --no-check-certificate https://busy4.me/node/opt/busy4me/menu-init -O /opt/busy4me/menu-init | logline
chmod +x /opt/busy4me/*
ls -la /opt/$PROJECT
echo "Start /opt/busy4me/update..." | logline
/bin/bash /opt/busy4me/update --full | logline

echo -e "\e[32m New groups: \e[33m" | logline
getent group $ADMIN_USER
getent group busyman | logline

# add tasks to crontab
# compare logs in every 10 min and reboot if notting happened
echo -e "\e[44m ................... update crontab \e[0m"
rm /etc/cron.d/compare_logs_reboot 2>/dev/null
cat > /etc/cron.d/compare_logs_reboot  << 'EOF'
*/10 * * * * root /bin/bash /opt/busy4me/compare_logs_reboot.sh
*/5 * * * * root export DISPLAY=:0 && export XAUTHORITY="/home/busyman/.Xauthority" && /bin/bash /opt/busy4me/windows-check.sh
EOF

date | logline
# update date before login....
echo -e "\e[36m update date....\e[33m" | logline
ntpdate -s time.nist.gov | logline
date | logline
sleep 1
echo -e "\e[35m apt-get --purge autoremove && apt-get clean.............................................."
sleep 1

apt-get -y remove exim4 exim4-base exim4-config exim4-daemon-light
apt-get -y autoremove exim4
rm -r /var/log/exim4/
rm -r /var/spool/mail/*

apt-get -qq --purge autoremove && apt-get clean


echo -e "\e[32m All done......................\e[0m" | logline
echo -e "Next to do: Run 'reboot' and should start google-chrome browser...." | logline
echo -e "Logifile: /var/log/busy4me.log" | logline
echo -e "\e[31m Reboot in 5s......................\e[0m" | logline

sleep 5
reboot
