#!/bin/bash
# Bootstrap script made by Visaroy, set varaibles, install salt, etc.

set -o nounset # unset variables as an error

__script_version="202"
__script_name="initiv"
__script_full_name="$0"
__script_arguments="$*"

if [ $USER != "root" ]; then
	echo -e "Run this script as root! exit..."
	exit
fi

# Autologin as vi user without login manager in console tty1...
__autologin_set () {
echo -e "\e[32m Autologin as vi user without login manager in console tty1...\e[0m"
mkdir -pv /etc/systemd/system/getty@tty1.service.d
rm /etc/systemd/system/getty@tty1.service.d/autologin.conf
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=-/sbin/agetty --autologin $busyuser --noclear %I $TERM
EOF
}

__autostart_set () {
cat > /home/vi/.profile  << EOF
[[ $(tty) = /dev/tty1 ]] && setterm -blank 0 -powersave off && startx
EOF
chown vi:vi /home/vi/.profile
}

__change_hostname () {
echo "host"
}

__help() {
	echo -e "========================= help ========================="
    cat << EOT

  Usage :  init [options] <action> [action-arguments]

  Options:
    -a Set user autologin in tty1 console
    -h  Display this message
    -v  Display script version
    -T  Pass hostname to
    -A  Pass the salt-master DNS name or IP. This will be stored under
        \${BS_SALT_ETC_DIR}/minion.d/99-master-address.conf
    -i  Pass the salt-minion id. This will be stored under
        \${BS_SALT_ETC_DIR}/minion_id

		-u  Update

		salt - install salt minion
  Actions:

EOT
}   # ----------  end of function __usage  ----------

__version() {
echo "$0 -- Version $__script_version"
}

__update () {
	echo "$0 -- Update $__script_version"
	if ! wget -nv -O ./initiv.new --no-check-certificate http://busy4.me/initiv; then
		echo -e "\e[101m\e[30m ERROR: there is no file "initiv" on the server or no response!...\e[0m"
		exit 1
	else
	rm -rf ./initiv
	cp ./initiv.new ./initiv 2>/dev/null
	chmod +x ./initiv
	exit 0
fi
}

while getopts ':ahvT:' opt
do
  case "${opt}" in
    a )  __help; exit 0                                          ;;
    h )  __help; exit 0                                          ;;
    v )  __version; exit 0                                       ;;
    T )  _NEW_HOSTNAME="$OPTARG"; echo ""                                       ;;
		u )  __update; exit 0                                          ;;
  esac
done

case $1 in
  "salt")
  ;;
  -as|--autologin-set)
    __autologin_set
  ;;
  -h|"-?")
    __help
  ;;
  -v)
    __version
  ;;
esac

systemctl set-default multi-user.target
