#!/bin/bash
#
PROJECT="busy4me"
#rm -R /opt/$PROJECT
#mkdir /opt/$PROJECT
#cd /opt/$PROJECT
#rm ./busy4me-init* && rm ./init*
#echo "wget -q --no-check-certificate https://busy4.me/opt/busy4me/*"

logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $SCRIPT - $line" | tee -a $LOGFILE 
    done
}

# install pyautogui and scrot from Debian repository
apt-get -y install python python-dev python-tk
apt-get -y install python-xlib scrot libtiff5-dev libjpeg62-turbo-dev
#apt-get -y install zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
apt-get install -y python-pip python-xlib python-pillow scrot
pip install setuptools -U # update 08-2019,
pip install pyautogui # need for automate keys, mouse, recognise pictures on the screen 

apt-get install -y python-opencv # necessary for advanced use pyautogui with cv2
pip install pillow imutils # necessary for advanced use pyautogui with cv2 like pyautogui.locateOnScreen(imag, confidence=0.9)


# Below methods will dowload and compile python-pillow, not realy necessary if you can install it from repo
# install Python 3, libraries, pyautogui, scrot and dependencies
#apt-get update
#apt-get install -y gcc # needed for Pillow compilation
#apt-get -y install python3 python3-dev
#apt-get -y install python3-pip python3-dev python3-tk scrot libtiff5-dev libjpeg62-turbo-dev
#apt-get -y install zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
#pip3 install python3_xlib
#pip3 install pyautogui
#pip3 install selenium

# install Python 2, libraries, pyautogui, scrot and dependencies
#apt-get update
#apt-get install -y gcc # needed for Pillow compilation
#apt-get -y install python python-dev
#apt-get -y install python-pip python-tk python-xlib scrot libtiff5-dev libjpeg62-turbo-dev
#apt-get -y install zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
#pip install pyautogui
