#!/bin/bash
PROJECT="busyman"
BUSYUSER=busyman
SCRIPT=init-1
LOGFILE=/var/log/${PROJECT}.log
chmod 777 /var/log/${PROJECT}.log

logline() {
  while IFS= read -r line; do
    echo "$(date +%F' '%T) $SCRIPT - $line" | tee -a $LOGFILE
  done
}
echo "$(date +%F' '%T) $SCRIPT - Start init-1 script ..." | logline

if [ $USER != "root" ]
  then
    echo -e "\e[31mRun this script as root! exit...\e[0m"
    echo "Run this script as root! exit..." | logline
  else
    echo -e "\e[32mRun OK as root...\e[0m" | logline
fi

# groupadd ${BUSYUSER} >> $LOGFILE
# useradd ${BUSYUSER} -s /bin/bash -m -g ${BUSYUSER} | logline
# add directory for write any files by users, chmod 777
# don't want to see any files in busyman directory, sometime it's seen on the screen when somehow open file dialog apears, in chrome Ctrl+o
# create directory with access for users
# add file .bash_aliases to root account
# install X, browser, and other packages
apt-get install -y software-properties-common | logline # for Debian
# added above if, to avoid double it
apt-get update | logline >> $LOGFILE

# download or update particular service (in this case project "busyman")
echo -e "\e[32m All done......................\e[0m" | logline
echo -e "Next to do: Run 'reboot' and should start google-chrome browser...." | logline
echo -e "Logifile: /var/log/${PROJECT}.log" | logline
echo -e "\e[31m Reboot PROJECT=${PROJECT} in 5s......................\e[0m" | logline
sleep 5
reboot
